export const GATES = [
  { type: 'Brama Garażowa', location: 'Nowy Świat 12' },
  { type: 'Szlaban', location: 'Puławska 7' },
  { type: 'Brama Główna', location: 'Chmielna 3' },
  { type: 'Wjazd Techniczny', location: 'Bracka 8' },
  { type: 'Bramka Wjazdowa', location: 'Sienna 5' },
  { type: 'Szlaban', location: 'Złota 2' },
  { type: 'Brama Garażowa', location: 'Mazowiecka 9' },
  { type: 'Brama Główna', location: 'Nowogrodzka 11' },
  { type: 'Wjazd Techniczny', location: 'Królewska 1' },
  { type: 'Bramka Wjazdowa', location: 'Mokotowska 6' },
  { type: 'Szlaban', location: 'Świętokrzyska 10' },
  { type: 'Brama Garażowa', location: 'Waryńskiego 4' },
  { type: 'Brama Główna', location: 'Żurawia 13' },
  { type: 'Wjazd Techniczny', location: 'Wiślana 14' },
  { type: 'Bramka Wjazdowa', location: 'Chmielna 15' },
  { type: 'Szlaban', location: 'Nowogrodzka 16' },
]
